### ISSUE TITLE
include option to skip conversion of existing files

### ISSUE THREAD

**Issue by meetar** [polygon-city/citygml-to-obj#3]
My conversion failed:

```
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

Restarting the conversion started from the beginning and overwrote existing files

**Comment by robhawkes** [comment]
I've added some basic logic to handle this for now, which should make processing of the larger datasets a little less cumbersome should things go wrong.

It's all pushed to the master branch so re-run `npm install ...` and follow the updated readme (moved to an options-based approach). Set `overwrite` to `true` if you want to forcefully overwrite any OBJ files that already exist, otherwise it will skip buildings that already have an OBJ file in the output directory (even if they were exported previously to this update).

Let me know how you get on.

**Comment by meetar** [comment]
:+1: Works great except now I'm apparently getting rate-limited by Bing – "Unable to retrieve elevation data" errors, but I suppose that's another issue :)
