### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by meetar** [polygon-city/citygml-to-obj#5]
Past a certain point, the process halts with

```
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Abort trap: 6
```

This was after a string of "Unable to convert building" errors, so there might be a leak somewhere.

**Comment by meetar** [comment]
Also saw this after starting from scratch – got through 2759 buildings this time, had stalled out previously at 2400.

**Comment by meetar** [comment]
So apparently once it's run out of memory, starting over and skipping existing buildings leaves it unable to access elevation data once it tries to convert a building it hasn't seen – so I'm guessing this is related to https://github.com/polygon-city/citygml-to-obj/issues/4 somehow.

**Comment by robhawkes** [comment]
I've not seen this yet, though I've not tried to crunch the full Mitte dataset yet. Whether or not it's related to the conversion errors, it certainly looks like I'm keeping references somewhere where I shouldn't be. I'll see what I can find.

**Comment by robhawkes** [comment]
More as a note-to-self…

After a cursory glance at a heap snapshot, the most likely culprits here are the `processQueue` array in `index.js` (getting overwhelmed with large, unprocessed XML – could pause the input stream when X items are in the queue as a fix) as well as something in the `worker.js` process. In the latter case, this might be because of an unreleased reference to previous buildings, or an issue with `fs.openSync`, the call to the external elevation endpoint, or `fs.outputFile`.

I'm not currently able to replicate a full on memory leak / out of memory error so testing these things may prove difficult.

**Comment by robhawkes** [comment]
I've just pushed 0.1.21 which pauses the input stream should there be delays with processing. This should prevent one obvious memory leak where it was possible for the backlog of buildings to grow much faster than they could be processed. With a small number of processor cores and a large dataset (like Mitte), this would most definitely result in a large amount of memory being gobbled up.

I'm curious if this has any effect on the memory errors you were seeing.

**Comment by robhawkes** [comment]
0.1.22 forcefully closes files that have been opened to see if models have already been converted. I'm still not convinced that this could have caused a memory issue but it can't hurt to ensure things are cleaned up.

**Comment by meetar** [comment]
no longer seeing problems :+1:
